name: etl_job_final_2s

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pytest pandas
          pip install dbt-core dbt-sqlite

      - name: Run ETL script
        run: python etl.py

      - name: Run Python tests
        run: pytest tests.py

      - name: Debug file structure
        run: |
          pwd
          ls -R

      - name: Create dbt profile
        run: |
          mkdir -p ~/.dbt
          echo "
          dbt_project:
            target: dev
            outputs:
              dev:
                type: sqlite
                threads: 1
                database: main
                schema: main
                schemas_and_paths:
                  main: etl.db
                schema_directory: .
                " > ~/.dbt/profiles.yml
      
      
      - name: Verify database exists
        run: |
          ls -l etl.db

      - name: Run dbt models
        run: dbt run --project-dir dbt_project

      - name: Run dbt tests
        run: dbt test --project-dir dbt_project



      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USER_NAME }}/etl-dbt-pipeline:latest
            ${{ secrets.DOCKER_USER_NAME }}/etl-dbt-pipeline:${{ github.sha }}