name: etl job_final

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install test dependenciesss
        run: pip install datetime
      
      - name: install test dependencies
        run: pip install pytest

      - name: install dependencies
        run: pip install pandas 

      - name: run etl-script
        run: python etl.py

      - name: run tests
        run: pytest tests.py

      - name : install dbt
        run: pip install dbt-core dbt-sqlite

      - name: Create dbt profile
        run: |
          mkdir -p ~/.dbt
          echo "
          dbt_project:
            target: dev
            outputs:
              dev:
                type: sqlite
                threads: 1
                database: 'etl.db'
                schema: main
                schemas_and_paths:
                  main: './'
                schema_directory: './'
          " > ~/.dbt/profiles.yml

    
      - name: Run dbt models
        run: |
          cd dbt_project
          dbt run

      - name: Run dbt tests
        run: |
          cd dbt_project
          dbt test