name: my_second_workflow

on:
  push:
    branches:
      - main

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - run: mkdir -p path/to/artifact
      - run: echo hello > path/to/artifact/dragon.txt

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: path/to/artifact/dragon.txt

      - name: List files
        run: ls -ltra

      - name: Run custom script
        run: |
          chmod +x script2.sh
          .github/script2.sh
