name: my_second_workflow

on:
  push:
    branches:
      - main

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create artifact directory
        run: mkdir -p path/to/artifact

      - name: Create dragon.txt
        run: echo hello > path/to/artifact/dragon.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: path/to/artifact/dragon.txt

      - name: List files
        run: ls -ltra

      - name: Run custom script
        run: |
          chmod +x .github/script2.sh
          ./.github/script2.sh