name : my_second_workflow

on : 
  push :
    branches : main

jobs : 
  first_job : 
    runs-on : ubuntu-latest

    steps : 

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v6.0.0
      
      - name : run_script
        run : ls -ltra 

      - name : run_script
        run : |
         chmod +x script2.sh
         ./script2.sh 
         
    


      
