name : my_first_workflow

on : 
  push :
    branches : main

jobs : 
  first_job : 
    runs-on : ubuntu-latest

    steps : 

      - name : list_files
        run : ls -ltra

      - name : run shell script 
        run : echo " hello from my file"
